services:
  ssh-server:
    build:
      context: .
      dockerfile_inline: |
        FROM ubuntu:latest
        RUN apt-get update && apt-get install -y openssh-server sudo
        RUN mkdir /run/sshd
        RUN echo 'root:${ROOT_PW:-123456}' | chpasswd
        RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
        RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd
        RUN sed -i 's/#Port 22/Port 1022/' /etc/ssh/sshd_config
        EXPOSE 1022
        CMD ["/usr/sbin/sshd", "-D"]
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /:/host/
      - /var/run/tappd.sock:/var/run/tappd.sock
      - /var/run/docker.sock:/var/run/docker.sock
  workload:
    image: nginx
